(turnerengineering.com.au)elena@~/websites/turnerengineering.com.au[development*] $ rs
Validating models...

INFO 2013-10-22 14:08:36,703 base 4750 139994148497152 Raven is not configured (logging is disabled). Please see the documentation for more information.
0 errors found
October 22, 2013 - 14:08:38
Django version 1.5.4, using settings 'project.settings'
Development server is running at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/elena/websites/turnerengineering.com.au/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 72, in __call__
    return self.application(environ, start_response)
  File "/home/elena/websites/turnerengineering.com.au/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 255, in __call__
    response = self.get_response(request)
  File "/home/elena/websites/turnerengineering.com.au/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 178, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/elena/websites/turnerengineering.com.au/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/elena/websites/turnerengineering.com.au/local/lib/python2.7/site-packages/django/views/debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/elena/websites/turnerengineering.com.au/local/lib/python2.7/site-packages/django/views/debug.py", line 298, in get_traceback_html
    return t.render(c)
  File "/home/elena/websites/turnerengineering.com.au/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/elena/websites/turnerengineering.com.au/local/lib/python2.7/site-packages/django/test/utils.py", line 66, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/elena/websites/turnerengineering.com.au/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/elena/websites/turnerengineering.com.au/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
Segmentation fault (core dumped)
